### ISSUE TITLE
gem install msgpack fails

### ISSUE THREAD

**Issue by ronakg** [msgpack/msgpack-ruby#130]
Hi,

I'm trying to install the neovim gem which in turn tries to install msgpack gem. However the installation always fails with following error:

```
$ gem install msgpack
Building native extensions.  This could take a while...
ERROR:  Error installing msgpack:
	ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/2.3.0/gems/msgpack-1.0.3/ext/msgpack
/usr/bin/ruby2.3 -r ./siteconf20170212-2901-dzsxp6.rb extconf.rb
checking for ruby/st.h... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/bin/$(RUBY_BASE_NAME)2.3
/usr/lib/ruby/2.3.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /usr/lib/ruby/2.3.0/mkmf.rb:587:in `try_cpp'
	from /usr/lib/ruby/2.3.0/mkmf.rb:1091:in `block in have_header'
	from /usr/lib/ruby/2.3.0/mkmf.rb:942:in `block in checking_for'
	from /usr/lib/ruby/2.3.0/mkmf.rb:350:in `block (2 levels) in postpone'
	from /usr/lib/ruby/2.3.0/mkmf.rb:320:in `open'
	from /usr/lib/ruby/2.3.0/mkmf.rb:350:in `block in postpone'
	from /usr/lib/ruby/2.3.0/mkmf.rb:320:in `open'
	from /usr/lib/ruby/2.3.0/mkmf.rb:346:in `postpone'
	from /usr/lib/ruby/2.3.0/mkmf.rb:941:in `checking_for'
	from /usr/lib/ruby/2.3.0/mkmf.rb:1090:in `have_header'
	from extconf.rb:3:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /var/lib/gems/2.3.0/extensions/x86_64-linux/2.3.0/msgpack-1.0.3/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /var/lib/gems/2.3.0/gems/msgpack-1.0.3 for inspection.
Results logged to /var/lib/gems/2.3.0/extensions/x86_64-linux/2.3.0/msgpack-1.0.3/gem_make.out
```

This is on Ubuntu 16.04.2 system.

**Comment by ronakg** [comment]
Content of the log at `/var/lib/gems/2.3.0/extensions/x86_64-linux/2.3.0/msgpack-1.0.3/mkmf.log`

```
"gcc -o conftest -I/usr/include/x86_64-linux-gnu/ruby-2.3.0 -I/usr/include/ruby-2.3.0/ruby/backward -I/usr/include/ruby-2.3.0 -I. -Wdate-time -D_FORTIFY_SOURCE=2   -g -O2 -
fstack-protector-strong -Wformat -Werror=format-security -fPIC conftest.c  -L. -L/usr/lib/x86_64-linux-gnu -L. -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -fstack-
protector -rdynamic -Wl,-export-dynamic     -lruby-2.3  -lpthread -lgmp -ldl -lcrypt -lm   -lc"
gcc: error: unrecognized command line option ‘-Wdate-time’
gcc: error: unrecognized command line option ‘-fstack-protector-strong’
checked program was:
/* begin */
1: #include "ruby.h"
2:
3: int main(int argc, char **argv)
4: {
5:   return 0;
6: }
/* end */
```

**Comment by ronakg** [comment]
Updating gcc to 4.9 fixed the issue.
