### ISSUE TITLE
Feature request: Time packer

### ISSUE THREAD

**Issue by marek22k** [msgpack/msgpack-ruby#353]
Hello,

in the Go implementation of msgpack there is a [Time Packer](https://github.com/vmihailenco/msgpack/blob/v5/time.go). Is it possible to implement the same?
```
{
            'Y' => 't'.ord,
            'M' => 11181,
            'S' => @session_id,
            'I' => current_id,
            'T' => Time.now,
            'E' => nil,
            'A' => nil
}.to_msgpack
```
```
/home/marek/.rvm/gems/ruby-3.2.2/gems/msgpack-1.7.2/lib/msgpack.rb:41:in `write': undefined method `to_msgpack' for 2023-11-05 19:37:36.838414893 +0100:Time (NoMethodError)

    packer.write v
          ^^^^^^
	from /home/marek/.rvm/gems/ruby-3.2.2/gems/msgpack-1.7.2/lib/msgpack.rb:41:in `pack'
	from /home/marek/.rvm/gems/ruby-3.2.2/gems/msgpack-1.7.2/lib/msgpack/core_ext.rb:11:in `to_msgpack'
```

**Comment by marek22k** [comment]
It seems that such a packer already exists, but is not activated by default: http://ruby.msgpack.org/MessagePack/Time.html
