### ISSUE TITLE
10 extra bytes after the deserialized object

### ISSUE THREAD

**Issue by marek22k** [msgpack/msgpack-ruby#356]
Hello,

the MessagePack Ruby Gem offers the functionality to read a file directly. However, this functionality seems to be broken:

```rb
require 'msgpack'

pp MessagePack.load("fac.msgpack")
```
results in
```
/home/marek/.rvm/gems/ruby-3.2.2/gems/msgpack-1.7.2/lib/msgpack.rb:32:in `full_unpack': 10 extra bytes after the deserialized object (MessagePack::MalformedFormatError)
	from /home/marek/.rvm/gems/ruby-3.2.2/gems/msgpack-1.7.2/lib/msgpack.rb:32:in `load'
	from a.rb:3:in `<main>'
```

```rb
require 'msgpack'

file = File.new "fac.msgpack", 'rb'
pp MessagePack.unpack file.read
file.close
```
results in
```
[1, 2, 6, 24, 120, 720]
```

[fac.msgpack.txt](https://github.com/msgpack/msgpack-ruby/files/13537785/fac.msgpack.txt)

**Comment by marek22k** [comment]
I have now taken a closer look at the source code and it seems that an IO stream or a binary string are required, but no file path.
